
# Security header presets
header remove "X-Powered-By"
header set "Strict-Transport-Security" "max-age=31536000; includeSubDomains; preload"
header set "Content-Security-Policy" "default-src 'self'; img-src *; script-src 'self'; object-src 'none'; require-trusted-types-for 'script'"
header set "X-Frame-Options" "SAMEORIGIN" always
header set "X-Content-Type-Options" "nosniff" always
header set "X-Permitted-Cross-Domain-Policies" "none" always
header set "Referrer-Policy" "no-referrer, strict-origin-when-cross-origin" always
header set "Permissions-Policy" "accelerometer=(none), camera=(none), fullscreen=(self), geolocation=(none), gyroscope=(none), interest-cohort=(), payment=(none), usb=(none), microphone=(none), magnetometer=(none)"
