# This file is required by acme-client included with OpenBSD
# These are the default parameters

authority letsencrypt {
        api url "https://acme-v02.api.letsencrypt.org/directory"
        account key "/etc/acme/letsencrypt-privkey.pem"
}


# Copy from /etc/hosting/generated/acme-domains.conf
include "/etc/hosting/acme-domains.conf"
